# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-23 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
